buildscript {
	repositories {
		google()
		mavenCentral()
		gradlePluginPortal()
	}
	dependencies {
		classpath "com.android.tools.build:gradle:${libs.versions.androidGradlePlugin.get()}"
		classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${libs.versions.kotlin}"
		classpath "org.jetbrains.kotlin:kotlin-serialization:${libs.versions.kotlin}"
		classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:${libs.versions.kotlin}"
	}
}

plugins {
	alias(libs.plugins.android.application)
	alias(libs.plugins.kotlin)
	alias(libs.plugins.kotlin.serialization)
	alias(libs.plugins.compose.compiler)
}

repositories {
	google()
	mavenCentral()
	gradlePluginPortal()
	exclusiveContent {
		forRepository {
			maven {
				url 'https://repo.mobile.jumio.ai'
			}
		}
		filter {
			includeGroup "com.jumio.android"
		}
	}
}

dependencies {
	implementation fileTree(dir: 'libs', include: '*.jar')

	// Kotlin
	implementation libs.kotlin
	// only for the sample code
	implementation libs.activity.ktx
	implementation libs.multidex
	implementation platform(libs.androidx.compose.bom)
	implementation libs.androidx.compose.material3
	implementation libs.androidx.compose.ui
	implementation libs.androidx.compose.ui.tooling.preview
	implementation libs.androidx.compose.activity
	implementation libs.androidx.compose.compiler
	implementation libs.androidx.compose.navigation
	implementation libs.kotlinx.serialization.json
	implementation libs.androidx.compose.lifecycle.runtime

	// Jumio dependencies
	implementation platform(libs.jumio.bom)
	implementation libs.jumio.core
	implementation libs.jumio.docfinder
	implementation libs.jumio.nfc
	implementation libs.jumio.barcode.mlkit
	implementation libs.jumio.defaultui
	implementation libs.jumio.digital.identity
	implementation libs.jumio.liveness
	implementation libs.jumio.camerax

	debugImplementation libs.androidx.compose.ui.tooling
}

android {
	compileSdkVersion 36
	buildToolsVersion "36.0.0"
	namespace "com.jumio.sample"

	defaultConfig {
		versionCode 1
		versionName "Jumio Sample"
		minSdkVersion 24
		targetSdkVersion 36
		multiDexEnabled true
		vectorDrawables.useSupportLibrary true
	}

	buildFeatures {
		// Determines whether to support View Binding.
		viewBinding true
		// Determines whether to support Data Binding.
		dataBinding false
		// Determines whether to support Jetpack Compose.
		compose true
	}

	compileOptions {
		sourceCompatibility 17
		targetCompatibility 17
	}

	kotlinOptions {
		jvmTarget = 17
	}

	lint {
		abortOnError false
	}

	buildTypes {
		debug {
		}
		release {
			minifyEnabled true
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
		}
	}

	packagingOptions {
		resources.pickFirsts.add("META-INF/versions/9/OSGI-INF/MANIFEST.MF")
		resources.pickFirsts.add("META-INF/kotlin-project-structure-metadata.json")
		resources.pickFirsts.add("META-INF/kotlinx_coroutines_core.version")
		resources.excludes.add("META-INF/androidx/**/LICENSE.txt")
		resources.excludes.add("META-INF/LICENSE.md")
		resources.excludes.add("META-INF/LICENSE-notice.md")
		resources.excludes.add("commonMain/**/*")
		resources.excludes.add("linuxMain/**/*")
		resources.excludes.add("nativeMain/**/*")
		resources.excludes.add("nonJvmMain/**/*")

		[
			"libsurface_util_jni.so",
			"libandroidx.graühics.path.so",
			"libimage_processing_util_jni.so",
			"libec4fd1.so",
			"libyuv_android.so",
			"libtensorflowlite_jni.so"
		].each { so ->
			it.excludes.add("lib/x86_64/$so")
			it.excludes.add("lib/x86/$so")
		}
	}

	composeOptions {
		// compose version must be compatible with kotlin version (version of org.jetbrains.kotlin:kotlin-gradle-plugin)
		// Refer to https://developer.android.com/jetpack/androidx/releases/compose-kotlin
		kotlinCompilerExtensionVersion = "${libs.versions.compose}"
	}
}